more c++ stuff

diff --git a/bin/agcc-bash-g++ b/bin/agcc-bash-g++
--- a/bin/agcc-bash-g++
+++ b/bin/agcc-bash-g++
@@ -69,25 +69,38 @@ TOOLCHAIN=$AGCC_NDK/toolchains/$AGCC_CXC-$AGCC_GCC
 PREBUILT=$TOOLCHAIN/prebuilt/linux-x86
 LDSCRIPTS=$PREBUILT/$AGCC_CXC/lib/ldscripts
 
-INC="-I$PLATFORM/usr/include"
-
-CPP="-D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -DANDROID -DSK_RELEASE -DNDEBUG -UDEBUG"
-
-WFLAGS="-Wall -Wno-unused -Wno-multichar -Wstrict-aliasing=2"
-
-CFLAGS="-march=armv5te -mtune=xscale -msoft-float -mthumb-interwork -fpic -fno-exceptions -ffunction-sections -funwind-tables -fmessage-length=0"
-
-OFLAGS="-O2 -finline-functions -finline-limit=300 -fno-inline-functions-called-once -fgcse-after-reload -frerun-cse-after-loop -frename-registers -fomit-frame-pointer -fstrict-aliasing -funswitch-loops"
-
-LDFLAGS="-Bdynamic -Wl,-T,$LDSCRIPTS/armelf_linux_eabi.x -Wl,-dynamic-linker,/system/bin/linker -Wl,--gc-sections -Wl,-z,nocopyreloc -Wl,--no-undefined -Wl,-rpath-link=$PLATFORM -L$PLATFORM/usr/lib -nostdlib $PLATFORM/usr/lib/crtend_android.o $PLATFORM/usr/lib/crtbegin_dynamic.o -lc $PREBUILT/lib/gcc/$AGCC_CXC/$AGCC_GCC/libgcc.a -lm -ldl"
-
-SHFLAGS="-nostdlib -Wl,-T,$LDSCRIPTS/armelf_linux_eabi.xsc -Wl,--gc-sections -Wl,-shared,-Bsymbolic -Wl,-rpath-link=$PLATFORM -L$PLATFORM/usr/lib -Wl,--no-whole-archive -lc -lm -Wl,--no-undefined $PREBUILT/lib/gcc/$AGCC_CXC/$AGCC_GCC/libgcc.a -Wl,--whole-archive"	# .a, .o input files go *after* here
-
-if [ "$CMD" == "g++" ]; then
-	:
+if [ "$CMD" = "g++" ] || [ "$CMD" = "c++" ]; then
+	CMD=g++
 else
-	CMD="gcc"
+	CMD=gcc
 fi
+
+INC=( -I$PLATFORM/usr/include )
+
+CPP=( -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__ -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__ -DANDROID -DSK_RELEASE -DNDEBUG -UDEBUG )
+
+WFLAGS=( -Wall -Wno-unused -Wno-multichar -Wstrict-aliasing=2 )
+
+CFLAGS=( -march=armv5te -mtune=xscale -msoft-float -mthumb-interwork -fpic -fno-exceptions -ffunction-sections -funwind-tables -fmessage-length=0 )
+
+OFLAGS=( -O2 -finline-functions -finline-limit=300 -fno-inline-functions-called-once -fgcse-after-reload -frerun-cse-after-loop -frename-registers -fomit-frame-pointer -fstrict-aliasing -funswitch-loops )
+
+LNFLAGS=( -Wl,-rpath-link=$PLATFORM/usr/lib -L$PLATFORM/usr/lib -L$PREBUILT/lib/gcc/$AGCC_CXC/$AGCC_GCC )
+
+LDFLAGS=( "${LNFLAGS[@]}" -Bdynamic -Wl,-T,$LDSCRIPTS/armelf_linux_eabi.x -Wl,-dynamic-linker,/system/bin/linker -Wl,--gc-sections -Wl,-z,nocopyreloc -Wl,--no-undefined -nostdlib $PLATFORM/usr/lib/crtend_android.o $PLATFORM/usr/lib/crtbegin_dynamic.o -lc -lm -ldl -lgcc )
+
+SHFLAGS=( "${LNFLAGS[@]}" -nostdlib -Wl,-T,$LDSCRIPTS/armelf_linux_eabi.xsc -Wl,--gc-sections -Wl,-shared,-Bsymbolic -Wl,--whole-archive )	# .a, .o input files go *after* here
+SHFLAGS_END=( -Wl,--no-whole-archive -lc -lm -lgcc )
+
+#if [ "$CMD" = "g++" ]; then
+#	LDFLAGS=( "${LDFLAGS[@]}" -Wl,-rpath-link=$AGCC_NDK/sources/cxx-stl/stlport/libs/armeabi -L$AGCC_NDK/sources/cxx-stl/stlport/libs/armeabi -lstlport_static -lgcc )
+#	SHFLAGS_END=( "SHFLAGS_END" -Wl,-rpath-link=$AGCC_NDK/sources/cxx-stl/stlport/libs/armeabi -L$AGCC_NDK/sources/cxx-stl/stlport/libs/armeabi -lstlport_shared -lgcc )
+#fi
+
+#if [ "$AGCC_CRYSTAX" != "" ]; then
+#	INC[${#INC[@]}]="-I$AGCC_NDK/sources/crystax/include"
+#	LNFLAGS=( -L$AGCC_NDK/sources/crystax/libs/armeabi/$AGCC_GCC -lcrystax_static -lgcc_eh "${LDFLAGS[@]}" )
+#fi
 
 # Now implement a quick parser for a gcc-like command line
 
@@ -95,7 +108,7 @@ MODE=DEFAULT
 OUT=
 WARN=0
 OPT=0
-ARGS=
+ARGS=( )
 SRC=0
 
 while true; do
@@ -123,6 +136,33 @@ while true; do
 				exit 1
 			fi
 			;;
+		-agcc-*)
+			case "$1" in
+				-agcc-cppflags)
+					echo "${CPP[@]}" "${INC[@]}"
+					;;
+				-agcc-cflags)
+					echo "${CFLAGS[@]}"
+					;;
+				-agcc-oflags)
+					echo "${OFLAGS[@]}"
+					;;
+				-agcc-wflags)
+					echo "${WFLAGS[@]}"
+					;;
+				-agcc-ldflags)
+					echo "${LDFLAGS[@]}"
+					;;
+				-agcc-shflags)
+					echo "${SHFLAGS[@]}" "${SHFLAGS_END[@]}"
+					;;
+				*)
+					echo "invalid agcc option" 1>&2
+					exit 1
+					;;
+			esac
+			exit 0
+			;;
 		*)
 			if [[ $1 =~ ^-W.* ]]; then
 				WARN=1
@@ -135,7 +175,7 @@ while true; do
 						SRC=1
 					fi
 					shopt -u nocasematch
-					ARGS="$ARGS $1"
+					ARGS[${#ARGS[@]}]="$1"
 				fi
 			fi
 			;;
@@ -176,35 +216,44 @@ fi
 
 # Assemble the command
 
-CMD="${PREBUILT}/bin/${AGCC_CXC}-${CMD}"
+if [ "$CMD" = "g++" ]; then
+	APPEND=( -std=c++98 )
+else
+	APPEND=( )
+fi
+CMD=( "${PREBUILT}/bin/${AGCC_CXC}-${CMD}" )
 if [ "$MODE" != DEFAULT ]; then
-	CMD="$CMD $MODE"
+	CMD[${#CMD[@]}]="$MODE"
 fi
 if [ "$OUT" != "" ]; then
-	CMD="$CMD -o $OUT"
+	CMD[${#CMD[@]}]="-o"
+	CMD[${#CMD[@]}]="$OUT"
 fi
 if [ $NEED_CPP -ne 0 ]; then
-	CMD="$CMD $INC $CPP"
+	CMD=( "${CMD[@]}" "${INC[@]}" "${CPP[@]}" )
 fi
 if [ $NEED_COMPILE -ne 0 ]; then
-	CMD="$CMD $CFLAGS"
+	CMD=( "${CMD[@]}" "${CFLAGS[@]}" )
 	if [ $WARN -ne 0 ]; then
-		CMD="$CMD $WFLAGS"
+		CMD=( "${CMD[@]}" "${WFLAGS[@]}" )
 	fi
 	if [ $OPT -ne 0 ]; then
-		CMD="$CMD $OFLAGS"
+		CMD=( "${CMD[@]}" "${OFLAGS[@]}" )
 	fi
 fi
 if [ $NEED_SHLINK -ne 0 ]; then
-	CMD="$CMD $SHFLAGS"
+	CMD=( "${CMD[@]}" "${SHFLAGS[@]}" )
 fi
-CMD="$CMD $ARGS"
+CMD=( "${CMD[@]}" "${ARGS[@]}" )
 if [ $NEED_LINK -ne 0 ]; then
-	CMD="$CMD $LDFLAGS"
+	CMD=( "${CMD[@]}" "${LDFLAGS[@]}" )
+fi
+if [ $NEED_SHLINK -ne 0 ]; then
+	CMD=( "${CMD[@]}" "${SHFLAGS_END[@]}" )
 fi
 
 if [ "$AGCC_ECHO" != "" ]; then
-	echo " <= $CMD"
+	echo " <= ${CMD[@]} ${APPEND[@]}"
 fi
 
-exec $CMD
+exec "${CMD[@]}" "${APPEND[@]}"
